import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: '<%= AppName %>',
  description: 'Generated by create-stack',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="app">
          <nav>
            <Link href="/">Home</Link>
<% if (modules.contact) { -%>
            <Link href="/contact">Contact</Link>
<% } -%>
<% if (modules.auth) { -%>
            <Link href="/login">Login</Link>
<% } -%>
<% if (modules.admin) { -%>
            <Link href="/dashboard">Dashboard</Link>
<% } -%>
          </nav>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
